version: '3'

services:
    ssh1:
        build: ./sshBox1
        ports:
            - "8888:22"
        container_name: ssh1
        links:
            - "ssh2:sshbox"
    ssh2:
        build: ./sshBox2
        container_name: ssh2
    ssh_python:
        build: ./pythonSshServer
        ports:
            - "3333:3333"
    node_game:
        build: ./nodeGame
        ports:
            - "7777:7777"
